#!/bin/sh
# SIMET-MA NetworkManager dispatcher script
# Copytight (c) 2023 NIC.br <medicoes@simet.nic.br>
#
# Distributed under the GPLv3+ license with additional terms and permissions
# Refer to the COPYING file on the program source for details

export LC_ALL=C
test -x /opt/simet/bin/simet_register_ma.sh || exit 0

[ "$2" = "connectivity-change" ] && [ "$CONNECTIVITY_STATE" = "FULL" ] || exit 0

( #subshell in background
  start-stop-daemon -c nicbr-simet --start --name simet_reg_ma \
	--startas /opt/simet/bin/simet_register_ma.sh \
	-- --boot || :
  exec invoke-rc.d simet-ma start
) </dev/null >/dev/null 2>&1 &
:
